services:
  web:
    build: ./php
    volumes:
      - ./src:/var/www

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: practice
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"